# Generated by Django 5.1.5 on 2025-01-24 02:06

from django.db import migrations
from django.db import transaction


def create_movie_index_page(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    Page = apps.get_model("wagtailcore.Page")
    MoviePageIndex = apps.get_model("wagtailmeili_testapp.MoviePageIndex")

    # Get the home page
    home_page = Page.objects.get(slug='home')
    movies_page_index_content_type = ContentType.objects.get_for_model(MoviePageIndex)
    default_locale = home_page.locale

    # Create the movie index page if it doesn't exist
    if not MoviePageIndex.objects.filter(slug='movies').exists():
        MoviePageIndex.objects.create(
                title="Movies",
                slug='movies',
                content_type=movies_page_index_content_type,
                path="000100010001",
                depth=home_page.depth + 1,
                numchild=0,
                url_path=f'{home_page.url_path}movies/',
                show_in_menus=True,
                locale=default_locale
        )


def remove_movie_index_page(apps, schema_editor):
    MoviePageIndex = apps.get_model('wagtailmeili_testapp.MoviePageIndex')
    MoviePageIndex.objects.filter(slug='movies').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmeili_testapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_movie_index_page, remove_movie_index_page),
    ]
