# Generated by Django 5.1.5 on 2025-01-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmeili_testapp', '0004_nonindexedmodel_nonindexedpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedMoviePage',
            fields=[
                ('moviepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailmeili_testapp.moviepage')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='wagtailmeili_testapp.author')),
                ('related_movies', models.ManyToManyField(blank=True, related_name='related_to', to='wagtailmeili_testapp.relatedmoviepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailmeili_testapp.moviepage',),
        ),
    ]
